name: ci

on:
  pull_request:
    branches:
      - "push_to_reg"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildxe
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          PR_NUMBER: ${{ github.event.number }}
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            memphisos/memphis-qa:latest
            memphisos/memphis-qa:${{ env.PR_NUMBER }}
